/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface definitions {
  /**
   * Topics and groups.
   */
  channels: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    inserted_at: string;
    slug: string;
  };
  /**
   * Individual messages sent by each user.
   */
  messages: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    inserted_at: string;
    message?: string;
    /**
     * Note:
     * This is a Foreign Key to `users.id`.<fk table='users' column='id'/>
     */
    user_id: string;
    /**
     * Note:
     * This is a Foreign Key to `channels.id`.<fk table='channels' column='id'/>
     */
    channel_id: number;
  };
  /**
   * Profile data for each user.
   */
  users: {
    /**
     * References the internal Supabase Auth user.
     *
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    username?: string;
    status?: "ONLINE" | "OFFLINE";
  };
}
